CREATE DATABASE IF NOT EXISTS EDU_Track;

USE EDU_Track;

CREATE TABLE STUDENT (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    GENDER VARCHAR(10),
    DOB DATE,
    DEPARTMENT VARCHAR(50),
    SEMESTER INT,
    CONTACT VARCHAR(20),
    ADDRESS VARCHAR(255)
);

CREATE TABLE FACULTY (
    FACULTY_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(50),
    CONTACT VARCHAR(20)
);

CREATE TABLE ADMIN (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE COURSE (
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    COURSE_CODE VARCHAR(20) UNIQUE NOT NULL,
    CREDIT_HOURS INT NOT NULL,
    FACULTY_ID INT,
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    SEMESTER INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    DATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GRADES (
    GRADE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    MARKS_OBTAINED DECIMAL(5,2),
    GRADE CHAR(2),
    SEMESTER INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FEE (
    FEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    AMOUNT_PAID DECIMAL(10,2) DEFAULT 0,
    DUE_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'Pending',
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID INT,
    RECIPIENT_ID INT,
    MESSAGE VARCHAR(255) NOT NULL,
    DATE_SENT DATETIME DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(20)
);

CREATE TABLE FEEDBACK (
    FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    FACULTY_ID INT,
    COURSE_ID INT,
    MESSAGE VARCHAR(255) NOT NULL,
    DATE_SUBMITTED DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO STUDENT (FULL_NAME, EMAIL, PASSWORD, GENDER, DEPARTMENT, SEMESTER)
VALUES ('Asjal Abdullah', 'asjal@student.com', '12345', 'Male', 'CS', 5);

INSERT INTO STUDENT (FULL_NAME, EMAIL, PASSWORD, GENDER, DEPARTMENT, SEMESTER)
VALUES ('Ali Raza', 'ali@student.com', '12345', 'Male', 'CS', 3);


INSERT INTO FACULTY (NAME, EMAIL, PASSWORD, DEPARTMENT)
VALUES ('Dr. Ahmed', 'ahmed@uni.com', '12345', 'CS');

INSERT INTO ADMIN (NAME, EMAIL, PASSWORD)
VALUES ('Super Admin', 'admin@edu.com', 'admin123');

SELECT * FROM STUDENT;

SELECT 
    STUDENT_ID,
    ROUND(
        (SUM(CASE WHEN STATUS='Present' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 
    2) AS ATTENDANCE_PERCENTAGE
FROM ATTENDANCE
WHERE STUDENT_ID = 1;



